apiVersion: v1
kind: Config
clusters:
  - name: authorize-service
    cluster:
      certificate-authority: /var/lib/minikube/certs/auth/ca.crt
      server: https://192.168.1.35:8443/v0/authorize

users:
  - name: authorize-api-server
    user:
      # This will come in the request header(Authorization) of above URL.
      # Can be used to validate if the request is coming from configured cluster
      token: test-token

current-context: webhook
contexts:
- context:
    cluster: authorize-service
    user: authorize-api-server
  name: webhook